name: CI

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: ros:kinetic-ros-core

    steps:
    - uses: /actions/checkout@v1
    - uses: ./
    - run: catkin_make
